Bdd projects
WildCodeSchool/lille-0920-js-p3-favart-backend pull request #5
Opened 2021-01-29 11:35 UTC by Fx-Colliot

2021-01-29 13:00 UTC, Thoms-C submitted a review, later dismissed
Seem ok to me !

2021-02-02 08:40 UTC, Marie-Garde submitted a review, later dismissed
Nice

2021-02-02 10:41 UTC, LoicBrassart requested changes
Please remove useless code

2021-02-02 10:41 UTC, LoicBrassart commented on index.js
> +});
Useless route

2021-02-05 14:48 UTC, Thoms-C approved these changes
Seem ok to me !

2021-02-08 13:06 UTC, LoicBrassart approved these changes
SnE

2021-02-08 13:11 UTC, merged